project:
  type: website

website:
  sidebar:
    style: "floating"
    search: true
    contents:
        - section: "Home"
          contents:
            - index.qmd
        - section: "Set-up"
          contents:
            - r.qmd
            - rstudio.qmd
        - section: "Getting started with R"
          contents:
            - basics.qmd
            - packages.qmd
            - data.qmd
            - tidyverse.qmd
        - section: "Doing and reporting"
          contents:
            - regression.qmd
            - imputation.qmd
            - plotting.qmd
            - table1.qmd
            - rmarkdown.qmd
        - section: "Going further with R"
          contents: 
            - functions.qmd
            - looping.qmd
        - section: "Practical applications"
          contents:
            - prediction.qmd
            - competing_risks.qmd
            - confounding.qmd
            - agreement.qmd
        - section: "Summary"
          contents: 
            - summary.qmd
            - further_resources.qmd
     
format:
  html:
    code-fold: true
    code-line-numbers: true
    code-summary: "Answer"
    theme: solar
    toc: false
    fig-cap-location: margin

editor: source
engine: knitr

execute:
  freeze: auto