project:
  type: website

website:
  sidebar:
    style: "floating"
    search: true
    contents:
        - section: "Home"
          contents:
            - index.qmd
        - section: "Getting started"
          contents:
            - r.qmd
            - rstudio.qmd
     
format:
  html:
    code-line-numbers: true
    code-link: true
    code-fold: true
    theme: solar
    toc: true
    toc-title: Contents
    toc-depth: 4
    toc-location: right
    fig-cap-location: margin

editor: source
engine: knitr

execute:
  freeze: auto