project:
  type: website

website:
  sidebar:
    style: "floating"
    search: true
    contents:
        - section: "Start"
          contents:
            - index.qmd
        - section: "Set-up"
          contents:
            - r.qmd
            - rstudio.qmd
        - section: "The basics"
          contents:
            - creating.qmd
            - using.qmd
            - packages.qmd
            - data.qmd
        - section: "Into the tidyverse"
          contents:
            - tidyverse.qmd
            - dplyr.qmd
            - tidyr.qmd
            - magrittr.qmd
        - section: "Into the multiverse"
          contents:
            - datatable.qmd
        - section: "New skills"
          contents: 
            - random.qmd
            - functions.qmd
            - looping.qmd
            - regex.qmd
        - section: "Workflow"
          contents:
            - scripts.qmd
            - rmarkdown.qmd
        - section: "General use"
          contents:
            - regression.qmd
            - plotting.qmd
            - table1.qmd
        - section: "Specific use"
          contents:
            - imputation.qmd
            - confounding.qmd
            - prediction.qmd
            - competing_risks.qmd
        - section: "Recap"
          contents: 
            - summary.qmd
            - further_resources.qmd
            - rython.qmd
            - slow.qmd
     
format:
  html:
    code-fold: true
    code-line-numbers: true
    code-summary: "Answer"
    theme: solar
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    fig-cap-location: bottom

editor: source
engine: knitr

execute:
  freeze: auto