project:
  type: website

website:
  sidebar:
    style: "floating"
    search: true
    contents:
        - section: "Home"
          contents:
            - index.qmd
        - section: "Getting started"
          contents:
            - r.qmd
            - rstudio.qmd
     
format:
  html:
    code-fold: true
    code-summary: "Answer"
    theme: solar
    toc: false
    fig-cap-location: margin

editor: source
engine: knitr

execute:
  freeze: auto